import torch_fidelity

def evaluate_model(real_images_dir: str, generated_images_dir: str):
    print("Starting model evaluation...")
    
    # Calculate all metrics using torch-fidelity
    metrics = torch_fidelity.calculate_metrics(
        input1=generated_images_dir,
        input2=real_images_dir,
        cuda=True,
        fid=True,
        isc=True,
        prc=True,
        verbose=False 
    )
    
    #  extract keys
    fid_score = metrics.get('frechet_inception_distance', 'N/A')
    is_mean = metrics.get('inception_score_mean', 'N/A')
    is_std = metrics.get('inception_score_std', 'N/A')
    
    precision = metrics.get('precision', 'N/A')
    recall = metrics.get('recall', 'N/A')

    print("=" * 45)
    print("         COMPLETE DIAGNOSTIC REPORT")
    print("=" * 45)
    
    if isinstance(fid_score, float):
        print(f"FID:       {fid_score:.4f}  (Lower is better)")
    else:
        print(f"FID:       {fid_score}")
        
    if isinstance(is_mean, float):
        print(f"IS:        {is_mean:.4f} ± {is_std:.4f}  (Higher is better)")
    else:
        print(f"IS:        {is_mean}")
        
    if isinstance(precision, float):
        print(f"Precision: {precision:.4f}  (Higher is better)")
    else:
        print(f"Precision: {precision}")
        
    if isinstance(recall, float):
        print(f"Recall:    {recall:.4f}  (Higher is better)")
    else:
        print(f"Recall:    {recall}")
    print("=" * 45)

# exec
real_dir = "./evaluation_data/real"
#path of real dataset like cifar-10 or imagenet
gen_dir = "./evaluation_data/real"
#path of the image generated by our elt modell

evaluate_model(real_dir, gen_dir)
